Repository uasoft-indonesia/badaso-nuxt, pull requests merged in 2021-06, with the labels that each got.

#11 Add labeler & funding info
  .github/FUNDING.yml
  .github/autolabeler.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yaml
Labels: enhancement

#13 Change nuxt-axios to axios
  lib/module.js
  lib/src/badaso.js
  package-lock.json
  package.json
  test/fixture/pages/crud.vue
Labels: bugfix, frontend

#14 Merge develop to main
  lib/module.js
  lib/src/badaso.js
  package-lock.json
  package.json
  test/fixture/pages/crud.vue
Labels: frontend

#15 Fix badaso blog module
  lib/src/badaso.js
  lib/src/plugin.js
  test/blog.test.js
  test/fixture/pages/blog.vue
  test/fixture/pages/crud.vue
  test/fixture/pages/index.vue
Labels: bugfix, frontend

#16 Merge develop to main
  lib/src/badaso.js
  lib/src/plugin.js
  test/blog.test.js
  test/fixture/pages/blog.vue
  test/fixture/pages/crud.vue
  test/fixture/pages/index.vue
Labels: frontend

#19 Fix content routing
  lib/src/plugin.js
Labels: bugfix

#20 Merge develop to main
  lib/src/plugin.js
Labels: frontend
